name: Build and Deploy GH Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Build produção
        run: |
          npx ng build --configuration production \
          --base-href "https://camilay3.github.io/portfolio/"

      - name: Configurar usuário Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy no GitHub Pages
        run: |
          npx angular-cli-ghpages \
          --dir=dist/portfolio/browser \
          --no-silent \
          --repo=https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
